# Generated by Django 4.1.2 on 2023-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIFO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('RFID', models.CharField(max_length=30)),
                ('Weight', models.FloatField()),
                ('Entry_date', models.DateField(auto_now_add=True)),
                ('Expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ManyToManyField(related_name='relation', to='FIFO.product')),
            ],
        ),
    ]
