# Generated by Django 4.1.2 on 2023-11-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIFO', '0002_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
