-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 16:34:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rfid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rfid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rfid` DEFAULT CHARACTER SET utf8 ;
USE `rfid` ;

-- -----------------------------------------------------
-- Table `rfid`.`id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rfid`.`id` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
